### ISSUE TITLE
closing square bracket before newline is not parsed correctly

### ISSUE THREAD

**Issue by sthiele** [y-ich/rust-sgf#1]
Hi, on the following example SGF
```
(;FF[4]GM[1]SZ[19]AP[SGFC:1.13b]
)
```
```node.get_text("AP").unwrap();```
returns
```SGFC:1.13b]``` but it should be ```SGFC:1.13b```

**Comment by y-ich** [comment]
Thank you!
I fixed by it as 0.1.5(1c2b85ab979df904ba7ea40f27b10ded5ed2030a).
Please check it.

**Comment by sthiele** [comment]
Works perfect.
Thank you!
